server:
  port: 9011
spring:
  application:
        name:
          auth-api
  datasource:
    url: jdbc:mysql://${cswap.db.host}:3306/cs_auth?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${cswap.db.pw}
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: localhost:8848
        namespace: dev
        group: campus-swap
        file-extension: yaml
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: campus-swap
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  profiles:
    active: dev
  security:
    oauth2:
      # for swagger
      authorization-server:
        token-uri: http://127.0.0.1:9011/oauth2/token
      client:
        registration:
          github:
            client-id: Ov23lio1pL4TnK5aL6mr
            client-secret: 1aec231de25cb3249df1eebd060928a5e88a7884
            redirect-uri: http://127.0.0.1:9011/login/oauth2/code/github
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 15
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000

logging:
  level:
    org.springframework.security: trace
    org.springframework.web: trace
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cswap.auth.controller

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:/com/cswap/auth/mapper/*.xml

swap:
  jwt:
    keyPairName: jwt.p12
    keyPairAlias: jwt
    keyPairSecret: 123456
    keyPairStoreSecret: 123456

