server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
#    nacos:
#      server-addr: 192.168.150.101:8848
    gateway:
      routes:
        - id: user
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/user/**

pe:
  auth:
    excludePaths:
      - /search/**
      - /user/login
      - /user/reg
      - /items/**
      - /hi

