spring:
  application:
    name: captcha-service
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: localhost:8848
        namespace: dev
        group: campus-swap
        file-extension: yaml
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: campus-swap
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  profiles:
    active: dev
  # for swagger
  security:
    oauth2:
      authorization-server:
        token-uri:
          http://127.0.0.1:9011/oauth2/token
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000
    #redisson:
    #配置文件目录
    #config: classpath:singleServerConfig.yaml
server:
  port: 63085
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    groups:
      enabled: true
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cswap.captcha.controller
