server:
  port: 63081
spring:
  application:
    name: product-api
  mvc:
    throw-exception-if-no-handler-found: true
  # for swagger
  security:
    oauth2:
      authorization-server:
        token-uri:
          http://127.0.0.1:9011/oauth2/token
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: localhost:8848
        namespace: dev
        group: campus-swap
        file-extension: yaml
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: campus-swap
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${cswap.db.host}:3306/cs_products?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${cswap.db.pw}
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000
  cache:
    type: redis
    redis:
      cache-null-values: true
      key-prefix: "CACHE:"
      time-to-live: 35600000
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
    listener:
      simple:
        acknowledge-mode: manual
    template:
      mandatory: true
    publisher-returns: true
    publisher-confirm-type: correlated









mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  mapper-locations: classpath:/com/cswap/product/mapper/*.xml



logging:
  level:
    com.cswap.product: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    groups:
      enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cswap.product.api

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表


cswap:
  jwt:
    header: Authorization
    expire: 604800
    secret: secretKey!secretKey!secretKey!secretKey!
    iss: zcy


feign:
  okhttp:
    enabled: true
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123